// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestao_cartoes_bancarios.Models;

#nullable disable

namespace gestao_cartoes_bancarios.Migrations
{
    [DbContext(typeof(DetalhesCartaoContext))]
    [Migration("20241002034347_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gestao_cartoes_bancarios.Models.DetalhesCartao", b =>
                {
                    b.Property<int>("DetalhesCartaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalhesCartaoId"));

                    b.Property<string>("CodigoDeSegurança")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DataDevalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NomeTitularCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("numeroCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("DetalhesCartaoId");

                    b.ToTable("DetalhesCartao");
                });
#pragma warning restore 612, 618
        }
    }
}
